FROM node:22-alpine

WORKDIR /app

COPY package.json .

RUN npm insall --ignore-scripts

COPY . .

RUN DATABASE_URL=$DATABASE_URL npx prisma generate
RUN DATABASE_URL=$DATABASE_URL npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]

